#cloud-config
autoinstall:
  version: 1
  locale: pt_BR.UTF-8
  keyboard:
    layout: br
    variant: abnt2
  identity:
    realname: "Alexandre Cardoso"
    hostname: "zolpidem"
    username: "alexandre"
    password: "6rounds=4096saltstr3X3TeYGnZx8Yl4zR5K8J9q2M2Q5J5X5K8J9q2M2Q5J"
  ssh:
    install-server: false

  storage:
    layout:
      name: direct
    config:
      - type: disk
        id: disk0
        match:
          size: largest
        ptable: gpt
        wipe: superblock
        grub_device: true
        partitions:
          - id: boot-efi
            size: 512M
            flag: boot
            grub_device: true
          - id: btrfs_root
            size: -1

      - type: format
        id: format-efi
        volume: boot-efi
        fstype: fat32

      - type: format
        id: format-btrfs
        volume: btrfs_root
        fstype: btrfs
        options: [compress=zstd:5, space_cache=v2]

      - type: mount
        device: format-efi
        path: /boot/efi

      - type: mount
        device: format-btrfs
        path: /
        options: [subvol=@, compress=zstd:5, space_cache=v2, discard=async, autodefrag, ssd, noatime]

      - type: mount
        device: format-btrfs
        path: /home
        options: [subvol=@home, compress=zstd:5, space_cache=v2, discard=async, autodefrag, ssd, noatime]

  package_update: false
  package_upgrade: false
  reboot: true